### ISSUE TITLE
debian 10.3 安装后进后台报错500

### ISSUE THREAD

**Issue by Omoinemie** [aaPanel/BaoTa#46]
系统版本：Debian 10.3
内核：5.3.18-2-pve
【现象】：
抱歉,程序异常
您请求的页面因发生异常而中断!
【错误日志】：
` File "class/common.py", line 75, in local
    self.GetOS()
  File "class/common.py", line 208, in GetOS
    tmp['osname'] = public.ReadFile('/etc/issue').split()[0]
IndexError: list index out of range
[2020-03-06 00:13:13,272] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/server/panel/BTPanel/__init__.py", line 254, in home
    comReturn = comm.local()
  File "class/common.py", line 75, in local
    self.GetOS()
  File "class/common.py", line 208, in GetOS
    tmp['osname'] = public.ReadFile('/etc/issue').split()[0]
IndexError: list index out of range
[2020-03-06 00:13:13,912] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/server/panel/BTPanel/__init__.py", line 254, in home
    comReturn = comm.local()
  File "class/common.py", line 75, in local
    self.GetOS()
  File "class/common.py", line 208, in GetOS
    tmp['osname'] = public.ReadFile('/etc/issue').split()[0]
IndexError: list index out of range
[2020-03-06 00:13:14,759] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/server/panel/BTPanel/__init__.py", line 254, in home
    comReturn = comm.local()
  File "class/common.py", line 75, in local
    self.GetOS()
  File "class/common.py", line 208, in GetOS
    tmp['osname'] = public.ReadFile('/etc/issue').split()[0]
IndexError: list index out of range
[2020-03-06 00:13:15,164] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/server/panel/BTPanel/__init__.py", line 254, in home
    comReturn = comm.local()
  File "class/common.py", line 75, in local
    self.GetOS()
  File "class/common.py", line 208, in GetOS
    tmp['osname'] = public.ReadFile('/etc/issue').split()[0]
IndexError: list index out of range
[2020-03-06 00:13:53,670] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/server/panel/BTPanel/__init__.py", line 254, in home
    comReturn = comm.local()
  File "class/common.py", line 75, in local
    self.GetOS()
  File "class/common.py", line 208, in GetOS
    tmp['osname'] = public.ReadFile('/etc/issue').split()[0]
IndexError: list index out of range
`

**Comment by logoove** [comment]
一样 wsl2 安装 debian 10.4 装不上宝塔
